version: '3.12'

services:
  db:
    image: postgres:15
    env_file:
      - ../.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - tabisync

  staging_tabisync:
    container_name: staging_tabisync
    build:
      context: .
      dockerfile: ./containers/django/Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=project_tabisync.settings
    env_file:
      - ../.env
    volumes:
      - .:/code
      - ../../web_app/tabisync/staging/shared/staticfiles:/code/project_tabisync/staticfiles
    ports:
      - "8001:8000"
    command: sh -c "/usr/local/bin/entrypoint.sh"
    networks:
      - tabisync

volumes:
  pgdata:

networks:
  tabisync:
      driver: bridge
