# Generated by Django 4.2.22 on 2025-06-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabisync', '0002_alter_itinerary_edit_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='edit_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='view_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
