# Generated by Django 4.2.22 on 2025-06-11 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabisync', '0003_alter_itinerary_edit_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='reset_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
