# Generated by Django 4.2.27 on 2026-02-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabisync', '0004_alter_itinerary_reset_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='design_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='total_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
