# Generated by Django 4.2.27 on 2026-03-03 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabisync', '0005_itinerary_design_number_itinerary_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WantToGo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('rating', models.FloatField(blank=True, null=True)),
                ('memo', models.TextField(blank=True)),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('stay_minutes', models.IntegerField(blank=True, null=True)),
                ('priority', models.IntegerField(default=3)),
                ('tag', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='want_to_go_list', to='tabisync.itinerary')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='tabisync.itinerary')),
            ],
            options={
                'ordering': ['date', 'order'],
            },
        ),
    ]
