# Generated by Django 4.2.27 on 2026-03-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabisync', '0006_wanttogo_schedulev2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wanttogo',
            name='planned_date',
        ),
        migrations.AddField(
            model_name='wanttogo',
            name='planned_day',
            field=models.IntegerField(default=0),
        ),
    ]
