# Generated by Django 4.2.29 on 2026-03-03 17:01

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tabisync', '0007_remove_wanttogo_planned_date_wanttogo_planned_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos_v2', to='tabisync.itinerary')),
            ],
        ),
    ]
