# Generated by Django 4.2.29 on 2026-03-03 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabisync', '0008_memov2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memov2',
            name='itinerary',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tabisync.itinerary'),
        ),
    ]
