# Generated by Django 4.2.29 on 2026-03-21 11:37

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tabisync', '0009_alter_memov2_itinerary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memov2',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='memov2',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='schedulev2',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='tabisync.wanttogo'),
        ),
        migrations.AlterField(
            model_name='memov2',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='memov2',
            name='itinerary',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memo_v2', to='tabisync.itinerary'),
        ),
        migrations.AlterField(
            model_name='schedulev2',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='wanttogo',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wanttogo',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wanttogo',
            name='place_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
