# Generated by Django 4.2.29 on 2026-03-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabisync', '0010_remove_memov2_created_at_remove_memov2_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulev2',
            name='day_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
