# Generated by Django 4.2.22 on 2026-08-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabisync', '0021_backfill_schedulev2_day_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulev2',
            name='day_index',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddIndex(
            model_name='schedulev2',
            index=models.Index(fields=['itinerary', 'day_index', 'start_time', 'order'], name='schedulev2_day_order_idx'),
        ),
    ]
