# Generated by Django 4.2.22 on 2026-08-06 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabisync', '0022_alter_schedulev2_day_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conciergechatlog',
            name='edit_action_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conciergechatlog',
            name='engine',
            field=models.CharField(blank=True, default='legacy', max_length=16),
        ),
        migrations.AddField(
            model_name='conciergechatlog',
            name='openai_call_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conciergechatlog',
            name='run_status',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='conciergechatlog',
            name='selected_skill_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='conciergechatlog',
            name='tool_call_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conciergechatlog',
            name='ui_component_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='ConciergeToolCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_index', models.PositiveIntegerField()),
                ('tool_id', models.CharField(max_length=64)),
                ('tool_version', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=16)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_type', models.CharField(blank=True, max_length=64)),
                ('args_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='tabisync.conciergechatlog')),
            ],
            options={
                'ordering': ['run_id', 'sequence_index'],
            },
        ),
    ]
