# Generated by Django 4.2.22 on 2026-08-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabisync', '0023_conciergechatlog_edit_action_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='管理画面の一覧にのみ表示。サイトには表示されない。', max_length=100, verbose_name='管理用タイトル')),
                ('message', models.TextField(max_length=500, verbose_name='表示メッセージ')),
                ('level', models.CharField(choices=[('info', '情報'), ('warning', '注意'), ('critical', '重要（メンテナンス等）')], default='info', max_length=10, verbose_name='重要度')),
                ('is_active', models.BooleanField(default=False, verbose_name='有効にする')),
                ('show_on_home', models.BooleanField(default=False, verbose_name='ホームページに表示')),
                ('show_on_all_itineraries', models.BooleanField(default=False, verbose_name='すべてのしおりページに表示')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='表示開始日時')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='表示終了日時')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('itineraries', models.ManyToManyField(blank=True, help_text='「すべてのしおりページに表示」がオフのとき、ここで指定したしおりにのみ表示します。', related_name='announcements', to='tabisync.itinerary', verbose_name='対象のしおり（個別指定）')),
            ],
        ),
    ]
