# Generated by Django 4.2.22 on 2026-08-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabisync', '0024_siteannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='conciergechatlog',
            name='web_search_call_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
